### ISSUE TITLE
There are legacy ReadConfig methods around

### ISSUE THREAD

**Issue by sebastianriese** [cloudandheat/ch-k8s-lbaas#3]
The following methods <https://github.com/cloudandheat/ch-k8s-lbaas/blob/master/internal/openstack/client.go#L60> are no longer required, as the config is now toml and the read functions are centralized in <https://github.com/cloudandheat/ch-k8s-lbaas/blob/master/internal/config/config.go>.

**Comment by sebastianriese** [comment]
A quick search through the code base shows that those functions are the only remaining uses of gcfg. So no other files need to be cleaned up.

**Comment by horazont** [comment]
Fixed in #5, used the wrong ID over there.
